In [1]:
#question 1
import numpy as np
x=np.random.rand(10,1)
print("Formed Matrix Is \n",x)

print("Mean Of The Above Matrix Is =",np.mean(x))

Formed Matrix Is 
 [[0.85890838]
 [0.15644741]
 [0.26800696]
 [0.28257836]
 [0.13520882]
 [0.2675436 ]
 [0.76158879]
 [0.68621378]
 [0.86258316]
 [0.82214139]]
Mean Of The Above Matrix Is = 0.5101220661738622


In [2]:
#Question 2

x=np.random.rand(20,1)
print("Formed Matrix Is \n",x)
print("Variance of the formed matrix is =",np.var(x))
print("Standard deviation of the formed matrix is =",np.std(x))

Formed Matrix Is 
 [[0.48246434]
 [0.63599787]
 [0.63138874]
 [0.20859732]
 [0.20708227]
 [0.46634764]
 [0.96704773]
 [0.10353811]
 [0.62056007]
 [0.97158017]
 [0.88024444]
 [0.31615738]
 [0.69881274]
 [0.51560171]
 [0.30003513]
 [0.61810842]
 [0.36519519]
 [0.07273597]
 [0.32260006]
 [0.10349969]]
Variance of the formed matrix is = 0.07342622501418401
Standard deviation of the formed matrix is = 0.2709727385073709


In [3]:
#Question 3

A=np.random.rand(10,20)
B=np.random.rand(20,25)

x=np.matmul(A,B)
print("Matrix Formed After Multiplication\n",x)

print("Sum Of Newly Formed Matrix = ",np.sum(x))

Matrix Formed After Multiplication
 [[4.92101742 4.97562747 5.70696775 4.38153971 3.36703739 3.77247388
  4.04994682 4.15588722 5.12248558 4.75129049 3.23075655 5.3130125
  4.47507149 4.46055359 4.67814232 5.74915269 3.02756175 4.40191924
  4.55857746 5.41703102 4.49744715 5.5642873  4.27340109 3.88813706
  4.25864404]
 [5.54350693 4.24726835 5.14334289 4.22425474 3.77270285 4.78022771
  4.27552841 5.38981191 5.2755202  4.69584865 3.91192998 5.07736858
  4.91055528 4.07324299 6.00819335 6.05253375 3.75081818 3.99610779
  4.21191623 4.94711789 4.85734839 6.18467797 4.82350572 4.3389694
  5.3039499 ]
 [5.78390133 5.35968996 5.87866155 4.54504116 4.44778906 4.30688891
  4.58081888 5.70711606 5.24613325 4.97956841 3.80368141 6.01518921
  4.95386759 4.61576199 5.16424303 6.27876037 3.45181747 4.2779649
  4.22308414 6.07145705 4.4432464  6.30644667 4.91684656 4.57743909
  5.31747151]
 [5.31482096 4.69321065 5.08127938 4.59548547 3.64646207 3.92661907
  4.11137778 5.50885359 5.02141087 4.7227

In [4]:
#Question 4
#f(x)=1 / (1 + exp(-x)) 
from math import exp
y=np.random.rand(10,1)
print(y)
l=[]
for i in y:
    l.append(1/(1+exp(-(i))))
    
print("\n\n\nAfter performing given function")
print(np.array(l).reshape(10,1))

[[0.71700316]
 [0.58909605]
 [0.75099462]
 [0.13969439]
 [0.85381686]
 [0.72128117]
 [0.72283461]
 [0.72090099]
 [0.80016473]
 [0.25408762]]



After performing given function
[[0.67194675]
 [0.64315771]
 [0.67939538]
 [0.53486691]
 [0.7013672 ]
 [0.67288908]
 [0.67323091]
 [0.67280539]
 [0.69000972]
 [0.56318235]]
